
additional_info: "TV OLV"

logging: false
use_custom_adstock: true
rolling: false
k: 2

weekly_seasonality: False
monthly_seasonality: True
annual_seasonality: False

# media channels
channels:
- media_netspend_brand_tv_new, 0.55
- media_netspend_brand_olv_total_new, 0.52
- total_media_netspend_brand_new_without_olvtv, 0.8
#- media_netspend_brand_ooh_new, 0.0
- media_spend_sea, 0.252
- media_spend_display_performance_sales, 0.466
#- media_netspend_brand_audio_total_new, 0.0
# media_netspend_brand_soc_olv_new, 0.0
#- media_spend_seo, 0.0
#- media_spend_kooperationen_partnering, 0.0


# negative control vars
controls_negative:
  - price_sim_effective_weighted
  - dummy_christmas
  #- activated_orders_unltd_dmnd
  #- price_hardware_resellers_effective_price_o2_unlimited_sum 


# positive control vars
controls_positive:
  - hw_per_transaction
  - brand_depot_index_o2
  - dummy_xl_launch
  - commission_per_transaction
  #- dummy_o2_grow_promotion
  - dummy_o2_mobile_portfolios_launch
  - dummy_black_friday
  - activated_orders_unltd_dmnd_dummy
  - dummy_iphone_launch
  #- total_kombivorteil_boost_normal_ao_share
  #- o2_kombivorteil
  #- total_kombivorteil_boost_normal_ao
  #- total_kombivorteil_boost_normal_ao_deviation_average

